[build]
target = "x86_64-pc-windows-gnullvm"

[target.x86_64-pc-windows-gnullvm]
linker = "C:/Users/Andrew/DEV/llvm-mingw/bin/x86_64-w64-mingw32-clang.exe"
rustflags = ["-L", "native=C:/Users/Andrew/Desktop/Saboteur/BRANDNEW/ACLibriary/.cargo/static/x64"]

[target.i686-pc-windows-gnullvm]
linker = "C:/Users/Andrew/DEV/llvm-mingw/bin/i686-w64-mingw32-clang.exe"
rustflags = ["-L", "native=C:/Users/Andrew/Desktop/Saboteur/BRANDNEW/ACLibriary/.cargo/static/x86"]